[package]
name = "schem-uploader"
version = "0.1.0"
authors = ["Naman Gupta <naman0311@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"